Introduce `add` family of commands for company IAM
mia-platform/miactl pull request #140
Opened 2024-01-03 09:28 UTC by JGiola

## What this PR is for?

This PR will introduce the new `add` family of command for `company iam`.

Those command are for:

- add a new user in a company with a given role
- create a new group in a company with a given role
- create a service account in a company with a given role
- add one or more user to an existing group in a company

2024-01-03 11:03 UTC, davidebianchi requested changes

2024-01-03 11:03 UTC, davidebianchi commented on internal/cmd/company/iam/group/create.go
> +	err := cmd.RegisterFlagCompletionFunc("role", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
Those roles should be dynamic? There is a role api, which could be used to dynamically configure this completion. What do you think?
In the future, probably the roles will change

2024-01-03 11:03 UTC, davidebianchi commented on internal/cmd/company/iam/group/create.go
> +	if !resources.IsValidServiceAccountRole(role) {
Also this check is static

2024-01-03 11:03 UTC, davidebianchi commented on internal/cmd/company/iam/user/create.go
> +	err := cmd.RegisterFlagCompletionFunc("role", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
Also here, static completion

2024-01-03 13:26 UTC, JGiola commented on CHANGELOG.md
> +
done

2024-01-03 13:26 UTC, JGiola commented on docs/30_commands.md
> +- `--output`, optional flag to save the service account json description in a file at the provided path
I've changed the docs to better reflect what we are saving

2024-01-04 14:32 UTC, davidebianchi approved these changes
LGTM

2024-01-04 14:32 UTC, merged