docs: removed default endpoint on command miactl context set CONTEXT …
mia-platform/miactl pull request #178
Opened 2024-04-03 12:15 UTC by alexBonadei

## What this PR is for?

After have installed miactl and created a new context I realized that the context `endpoint` did not have a default. I had to set it manually with this value `https://console.cloud.mia-platform.eu` (that was the one documented as default).

2024-04-03 12:52 UTC, fredmaggiowski commented
I'd rather actually implement the default, instead of changing the doc 🤔 

@JGiola what do you think about it? Is there a reason why the default is not applied?

2024-04-03 14:00 UTC, JGiola commented
The doc is wrong, probably a copy paste from the holdover when miactl didn't have the context functionality.

It's correct to remove it from the doc pages because the current flag help text doesn't mention it.

I don't remember right now if the default value wasn't preserved in the context creation for a mistake or for a valid reason...

2024-04-03 14:54 UTC, fredmaggiowski approved these changes
LGTM

2024-04-03 15:41 UTC, JGiola requested changes
Before merging, can you remove all the other references to this default in the same file?

2024-04-04 08:02 UTC, JGiola requested changes

2024-04-04 08:02 UTC, JGiola commented on go.mod
Can you leave out the go.mod and go.sum from the commit, you are only changing doc files...

2024-04-04 08:52 UTC, JGiola approved these changes
LGTM

2024-04-04 08:53 UTC, merged