feat: printer interface and migration of all commands
mia-platform/miactl pull request #202
Opened 2024-06-20 20:43 UTC by fredmaggiowski

## What this PR is for?

This PR addresses #201 proposing the printer interface provided by the `clioptions` package, in order to provide the means for a centralized and standardized render method

**Which issue(s) this PR fixes:**

- Fixes #201 

The Printer interface follows the spec from issue #201 but I've also added basic options management, specifically for wrap lines which have been disabled for certain commands

2024-06-20 20:59 UTC, fredmaggiowski commented on internal/cmd/marketplace/apply/table.go
> +	// FIXME: should use the printer from clioptions!
This has been a pain to try and migrate. I've put a FIXME for a future PR

2024-06-21 07:06 UTC, malta895 commented on internal/cmd/marketplace/list.go
> +func getMarketplaceItemsTable(context context.Context, client *client.APIClient, options GetMarketplaceItemsOptions, p printer.IPrinter) error {
I would now rename this to `printMarketplaceItemsTable`

2024-06-21 08:41 UTC, JGiola requested changes
Can you also rebase the branch with main?

2024-06-21 08:41 UTC, JGiola commented on CHANGELOG.md
> +### Refactor
```suggestion
### Changed
```

2024-06-21 09:10 UTC, JGiola approved these changes

2024-06-21 09:10 UTC, JGiola approved these changes

2024-06-21 09:11 UTC, merged